# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cedf07651177d33cfaf92a7f542a868077b76e234546736f811fdfd91ca934370a7f45567d54a298fd97fcbfb44ea27c9d404e0f18090f400c2b195ed440663a
  #Facebook
  facebook_key: '1661159680839128'
  facebook_secret: '12183aa239087e60cc1b3faf791edbaf'

  #Google
  google_key: "460581299641-ns66cegoeq609bq8pmsf968dlpdmc0jl.apps.googleusercontent.com"
  google_secret: "c-TDCRdwAtsUeEgvqlAwJzOF"

test:
  secret_key_base: d5b3aeb661f6a38af8dac499c3c7ec03d356c7ff35df5f18eef59e8cda2e0c5307e6e78eb06b7be486dc3b41c3d1b4c96389749ce6469c531d1ffd9b3e3708b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
